services:
  main:
    container_name: main
    image: ghcr.io/gabrielroot/flask-nu-box:latest
    environment:
      TZ: America/Sao_Paulo
      ENV_FOR_DYNACONF: development
    expose:
      - '80'
    volumes:
      - '.:/usr/src/app'
    healthcheck:
      test: ["CMD", "curl", "-f", "-H", "Accept: text/html", "http://localhost/auth/login"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - flaskk
networks:
  flaskk:
    driver: bridge
