version: '3.2'

services:
  main:
    container_name: main
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    volumes:
      - .:/usr/src/app
    depends_on:
      - db
    networks:
      - flaskk

  adminer:
    container_name: adminer
    image: adminer
    ports:
      - 8080:8080
    networks:
      - flaskk
    depends_on:
      - db

  db:
    container_name: db
    image: postgres:10-alpine
    env_file: .env
    ports:
      - 5432:5432
    volumes:
      - ./.docker/data:/var/lib/postgresql/data
    networks:
      - flaskk

networks:
  flaskk:
    driver: bridge
