"""Added some column constraints.

Revision ID: a739c612d2db
Revises: 00a17e17cbad
Create Date: 2023-03-31 22:33:54.517645

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a739c612d2db'
down_revision = '00a17e17cbad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('balances', schema=None) as batch_op:
        batch_op.alter_column('total',
               existing_type=sa.NUMERIC(),
               nullable=False)

    with op.batch_alter_table('boxes', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('value',
               existing_type=sa.NUMERIC(),
               nullable=False)
        batch_op.alter_column('goal',
               existing_type=sa.NUMERIC(),
               nullable=False)

    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.alter_column('operation',
               existing_type=sa.VARCHAR(length=140),
               nullable=False)
        batch_op.alter_column('value',
               existing_type=sa.NUMERIC(),
               nullable=False)
        batch_op.alter_column('date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(length=140),
               nullable=False)
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=512),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=512),
               nullable=True)
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(length=140),
               nullable=True)

    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.alter_column('date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
        batch_op.alter_column('value',
               existing_type=sa.NUMERIC(),
               nullable=True)
        batch_op.alter_column('operation',
               existing_type=sa.VARCHAR(length=140),
               nullable=True)

    with op.batch_alter_table('boxes', schema=None) as batch_op:
        batch_op.alter_column('goal',
               existing_type=sa.NUMERIC(),
               nullable=True)
        batch_op.alter_column('value',
               existing_type=sa.NUMERIC(),
               nullable=True)
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)

    with op.batch_alter_table('balances', schema=None) as batch_op:
        batch_op.alter_column('total',
               existing_type=sa.NUMERIC(),
               nullable=True)

    # ### end Alembic commands ###
