# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.7
      uses: actions/setup-python@v3
      with:
        python-version: "3.7"
    - name: Install project dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements-dev.txt ]; then pip install -r requirements-dev.txt; fi
    - name: Inject settings from secrets
      run: echo ${{ secrets.SETTINGS_TOML }} > settings.toml
    - name: "Setting locale info"
      run: |
        #sudo apt-get -y update && apt-get -y install locales locales-all
        export LANG=pt_BR.UTF-8  
        export LANGUAGE=pt_BR:en  
        export LC_ALL=pt_BR.UTF-8 
    - name: Check imports sorting & lint with flake8
      run: |
        make pep8
    - name: Test with pytest
      run: |
        make test
